export const feeds = {

vc: [
  'https://babyvc.substack.com/feed',
  'https://avilavc.substack.com/feed',
  'https://shrutigandhi.substack.com/feed',
  'https://akashbajwa.substack.com/feed',
  'https://grounded.substack.com/feed',
  'https://nextgenvc.substack.com/feed',
  'https://newsletter.mcj.vc/feed',
  'https://thegeneralist.substack.com/feed',
  'https://chudson.substack.com/feed',
  'https://firstfollowers.substack.com/feed',
  'https://williamcordeiro.substack.com/feed',
  'https://whoisnnamdi.substack.com/feed',
  'https://goodai.substack.com/feed',
  'https://multiple.substack.com/feed',
  'https://theventurecrew.substack.com/feed',
  'https://ventureupward.substack.com/feed',
  'https://healthvc.substack.com/feed',
  'https://chrismccann.substack.com/feed',
  'https://www.thescenarionist.org/feed',
  'https://www.newcomer.co/feed',
  'https://ventureunlocked.substack.com/feed',
  'https://ideas.scotthartley.com/feed',
  'https://indiscretemusings.substack.com/feed',
  'https://dtvc.substack.com/feed',
  'https://nbt.substack.com/feed',
  'https://sajithpai.substack.com/feed',
  'https://www.howtolandinventurecapital.com/feed',
  'https://corporateventurecapital.substack.com/feed',
  'https://smallsteps.substack.com/feed',
  'https://climateventuresvco2.substack.com/feed',
],

english: [
  'https://timdenning.substack.com/feed',
  'https://niallharbison.substack.com/feed',
  'https://ravenewworld.substack.com/feed',
  'https://thegeneralist.substack.com/feed',
  'https://www.oneusefulthing.org/feed',   
  'https://newsletter.mcj.vc/feed',
],

// lithuanian: [
//   'https://vartotojogidas.substack.com/feed',
//   'https://emilijaviso.substack.com/feed',
//   'https://gustestulpin.substack.com/feed',
//   'https://domasraibys.substack.com/feed',
//   'https://malonumui.substack.com/feed',
// ],

ai: [
  'https://fintechbusinessweekly.substack.com/feed',
  'https://interlinked.substack.com/feed',
  'https://chamath.substack.com/feed',
  'https://blog.bytebytego.com/feed',
  'https://fintechbusinessweekly.substack.com/feed',
  'https://www.understandingai.org/feed',
  'https://kyla.substack.com/feed',
  'https://theconvivialsociety.substack.com/feed',
  'https://importai.substack.com/feed',
]

};