services:
  - type: private
    name: feed-fetcher
    env: node
    buildCommand: npm install
    startCommand: node src/feed-fetcher/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: note
          property: connectionString

  - type: cron
    name: fetch-articles
    env: node
    schedule: 0 0 * * *
    buildCommand: npm install
    startCommand: "curl -X POST https://api.render.com/v1/services/YOUR_SERVICE_ID/jobs -H 'Authorization: Bearer $RENDER_API_KEY'"
    envVars:
      - fromGroup: note-env