services:
  - type: web
    name: feed-fetcher
    env: node
    region: virginia
    buildCommand: npm install && npx prisma generate
    startCommand: node src/feed-fetcher/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: note
          property: connectionString
      - key: PORT
        value: 3000

  - type: cron
    name: fetch-articles
    env: node
    region: virginia
    schedule: 0 0 * * *
    buildCommand: npm install
    startCommand: "curl -X POST https://YOUR_SERVICE_URL/fetch -H 'Authorization: Bearer $RENDER_API_KEY'"
    envVars:
      - fromGroup: note-env